### ISSUE TITLE
meshlabserver discontinued

### ISSUE THREAD

**Issue by yvanblanchard** [zhangty019/remesh_bat#1]
Notice that starting from MeshLab v2020.12, the meshlabserver does not exist anymore, and was replaced by pyMeshLab (runnning mlx scripts through Python).

https://stackoverflow.com/questions/65825861/where-is-meshlabserver-exe-in-2020-12

**Comment by yvanblanchard** [comment]
Maybe you could update the ReadMe (recommanded MeshLab version) for this repo, but also this one:
https://github.com/zhangty019/S3_DeformFDM
..with either a note on the max version number of meshlab (for meshlabserver), or using a new methodology with the new python system.

Older versions here:
https://github.com/cnr-isti-vclab/meshlab/releases
https://meshlab.software.informer.com/versions/

**Comment by zhangty019** [comment]
Thanks, now the remesh method is updated by using pyMeshLab 
[remesh.zip](https://github.com/zhangty019/remesh_bat/files/11041662/remesh.zip)

**Comment by zhangty019** [comment]
And the ReadMe is updated.

**Comment by yvanblanchard** [comment]
@zhangty019  For your information, there is also the isotropic remesher algorithm here (in order to prevent using MeshLab):
https://github.com/huxingyi/isotropicremesher

**Comment by zhangty019** [comment]
Many thanks
